# Generated by Django 5.2.5 on 2025-10-06 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('10-0-1', 'Llamado Estructural'), ('10-0-2', 'Llamado a Vehículo'), ('10-1', 'Incendio Forestal'), ('10-2', 'Rescate Vehicular'), ('10-3', 'Rescate de Personas'), ('10-4', 'Materiales Peligrosos'), ('Otro', 'Otro')], default='Otro', max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_hora_alarma', models.DateTimeField()),
                ('descripcion', models.TextField(verbose_name='Detalles del Incidente')),
                ('unidades_despachadas', models.CharField(help_text='Ej: B-1, R-2, Z-3', max_length=100)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Controlada', 'Controlada'), ('Finalizada', 'Finalizada')], default='Activa', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('oficial_a_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora_alarma'],
            },
        ),
        migrations.CreateModel(
            name='SalidaTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_hora_salida', models.DateTimeField()),
                ('fecha_hora_regreso', models.DateTimeField(blank=True, null=True)),
                ('unidades_involucradas', models.CharField(help_text='Ej: B-1, R-2, Z-3', max_length=100)),
                ('descripcion', models.TextField(blank=True, verbose_name='Reporte / Novedades')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_creadas', to=settings.AUTH_USER_MODEL)),
                ('personal_a_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora_salida'],
            },
        ),
    ]
