# Generated by Django 5.2.5 on 2025-10-07 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=150)),
                ('cupos', models.PositiveIntegerField(blank=True, help_text='Dejar en blanco si no hay límite', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asistentes', models.ManyToManyField(blank=True, related_name='capacitaciones_asistidas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacitaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
