# Generated by Django 5.2.5 on 2025-10-07 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_mantenimiento_archivomantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo', models.CharField(blank=True, help_text='Código o número de serie único', max_length=50, null=True, unique=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('ubicacion', models.CharField(help_text='Ej: Bodega 1, Carro B-2', max_length=150)),
                ('estado', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('En Reparación', 'En Reparación'), ('De Baja', 'De Baja')], default='Bueno', max_length=20)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('agregado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
