# Generated by Django 5.2.5 on 2025-10-10 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_cajachica'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaterreno',
            name='kilometraje_regreso',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje de Regreso'),
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='kilometraje_salida',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometraje de Salida'),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='descripcion',
            field=models.TextField(verbose_name='Reporte / Novedades'),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='unidades_involucradas',
            field=models.CharField(max_length=200),
        ),
    ]
