# Generated by Django 4.2.23 on 2025-10-15 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_salidaterreno_kilometraje_regreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Reporte / Novedades'),
        ),
    ]
