# Generated by Django 4.2.23 on 2025-10-15 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_proyecto_creado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='inventario',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_asignado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='agregado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_agregado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(choices=[('Casco de bombero', 'Casco de bombero (F1, F2, etc.)'), ('Equipo de respiración autónoma (ERA)', 'Equipo de respiración autónoma (ERA)'), ('Traje estructural', 'Traje estructural (chaquetón y pantalón)'), ('Botas estructurales', 'Botas estructurales'), ('Guantes de bombero', 'Guantes de bombero'), ('Monja / capucha ignífuga', 'Monja / capucha ignífuga'), ('Linterna para casco', 'Linterna para casco'), ('Hacha de bombero', 'Hacha de bombero'), ('Herramienta Halligan', 'Herramienta Halligan'), ('Manguera de 1.5 pulgadas', 'Manguera de 1.5"'), ('Manguera de 2.5 pulgadas', 'Manguera de 2.5"'), ('Pitón / Lanza de agua', 'Pitón / Lanza de agua'), ('Escala de extensión', 'Escala de extensión'), ('Cámara térmica', 'Cámara térmica'), ('Detector de gases', 'Detector de gases'), ('Otro', 'Otro (especificar en descripción)')], default='Otro', max_length=200),
        ),
    ]
