# Generated by Django 4.2.23 on 2025-10-22 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_inventario_cantidad_remove_inventario_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario', to='usuarios.compania'),
        ),
    ]
