# Generated by Django 6.0.2 on 2026-03-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_inventario_compania'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='ver_capacitaciones',
            field=models.BooleanField(default=False, verbose_name='Capacitaciones'),
        ),
        migrations.AddField(
            model_name='rol',
            name='ver_documentacion',
            field=models.BooleanField(default=False, verbose_name='Documentación'),
        ),
        migrations.AddField(
            model_name='rol',
            name='ver_emergencias',
            field=models.BooleanField(default=False, verbose_name='Emergencias'),
        ),
        migrations.AddField(
            model_name='rol',
            name='ver_escanear_qr',
            field=models.BooleanField(default=False, verbose_name='Escanear QR'),
        ),
        migrations.AddField(
            model_name='rol',
            name='ver_inventario',
            field=models.BooleanField(default=False, verbose_name='Inventario'),
        ),
        migrations.AddField(
            model_name='rol',
            name='ver_mantenimientos',
            field=models.BooleanField(default=False, verbose_name='Mantenimientos'),
        ),
        migrations.AddField(
            model_name='rol',
            name='ver_salidas_terreno',
            field=models.BooleanField(default=False, verbose_name='Salidas a terreno'),
        ),
    ]
