# Generated by Django 6.0.2 on 2026-03-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_rol_ver_capacitaciones_rol_ver_documentacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='ver_proyectos',
            field=models.BooleanField(default=False, verbose_name='Proyectos'),
        ),
    ]
