# Generated by Django 6.0.2 on 2026-03-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_rol_ver_proyectos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacitacion',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='malla',
            field=models.CharField(choices=[('Nivel postulante', 'Nivel postulante'), ('Nivel inicial', 'Nivel inicial'), ('Nivel operativo', 'Nivel operativo'), ('Nivel profesional', 'Nivel profesional'), ('Nivel especialidad', 'Nivel especialidad'), ('Otros', 'Otros')], default='Otros', max_length=50, verbose_name='Malla/Curso'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='ver_capacitaciones',
            field=models.BooleanField(default=False, verbose_name='Cursos'),
        ),
    ]
