# Generated by Django 6.0.2 on 2026-03-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_capacitacion_options_capacitacion_malla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='ver_resumen_general',
            field=models.BooleanField(default=False, verbose_name='Resumen General'),
        ),
    ]
