# Generated by Django 6.0.2 on 2026-03-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_rol_ver_resumen_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='editar_capacitaciones',
            field=models.BooleanField(default=False, verbose_name='Editar Cursos'),
        ),
        migrations.AddField(
            model_name='rol',
            name='editar_documentacion',
            field=models.BooleanField(default=False, verbose_name='Editar Documentación'),
        ),
        migrations.AddField(
            model_name='rol',
            name='editar_emergencias',
            field=models.BooleanField(default=False, verbose_name='Editar Emergencias'),
        ),
        migrations.AddField(
            model_name='rol',
            name='editar_inventario',
            field=models.BooleanField(default=False, verbose_name='Editar Inventario'),
        ),
        migrations.AddField(
            model_name='rol',
            name='editar_mantenimientos',
            field=models.BooleanField(default=False, verbose_name='Editar Mantenimientos'),
        ),
        migrations.AddField(
            model_name='rol',
            name='editar_proyectos',
            field=models.BooleanField(default=False, verbose_name='Editar Proyectos'),
        ),
        migrations.AddField(
            model_name='rol',
            name='editar_salidas_terreno',
            field=models.BooleanField(default=False, verbose_name='Editar Salidas a terreno'),
        ),
    ]
