# Generated by Django 6.0.2 on 2026-03-16 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_rol_editar_capacitaciones_rol_editar_documentacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='usuarios.compania'),
        ),
    ]
