# Generated by Django 6.0.2 on 2026-03-16 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_documento_compania'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajachica',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='usuarios.compania'),
        ),
        migrations.AddField(
            model_name='rol',
            name='editar_caja_chica',
            field=models.BooleanField(default=False, verbose_name='Editar Caja Chica'),
        ),
        migrations.AddField(
            model_name='rol',
            name='ver_caja_chica',
            field=models.BooleanField(default=False, verbose_name='Caja Chica'),
        ),
    ]
