# Generated by Django 4.2.23 on 2026-03-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_cajachica_compania_rol_editar_caja_chica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave_radial',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Clave Radial'),
        ),
    ]
