# Generated by Django 4.2.23 on 2026-03-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_usuario_clave_radial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20),
        ),
    ]
