# Generated by Django 4.2.23 on 2026-04-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='companias_invitadas',
            field=models.ManyToManyField(blank=True, related_name='capacitaciones_invitadas', to='usuarios.compania'),
        ),
    ]
