# Generated by Django 4.2.30 on 2026-04-10 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_capacitacion_companias_invitadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='compania_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_pagados', to='usuarios.compania', verbose_name='Caja de Compañía'),
        ),
    ]
