# Generated by Django 4.2.30 on 2026-04-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_mantenimiento_compania_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='compania',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_companias/', verbose_name='Logo de la Compañía'),
        ),
    ]
