# Generated by Django 4.2.30 on 2026-08-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_aviso_rol_editar_avisos_rol_ver_avisos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='tipo_actividad',
            field=models.CharField(choices=[('Curso', 'Curso'), ('Reunión', 'Reunión'), ('Taller', 'Taller'), ('Charla', 'Charla'), ('Visita', 'Visita'), ('Otro', 'Otro')], default='Curso', max_length=50, verbose_name='Tipo de Actividad'),
        ),
    ]
