# Generated by Django 4.2.30 on 2026-08-06 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_capacitacion_tipo_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('General', 'Documento General'), ('Orden del Día', 'Orden del Día'), ('Circular', 'Circular'), ('Formulario', 'Formulario'), ('Otro', 'Otro')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='emergencias_asistidas', to=settings.AUTH_USER_MODEL, verbose_name='Personal Asistente'),
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='usuarios.compania')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='usuarios.carpeta'),
        ),
    ]
