# Generated by Django 4.2.30 on 2026-08-06 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_documento_tipo_emergencia_asistentes_carpeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='es_privado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, related_name='carpetas_permitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='es_privado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, related_name='documentos_permitidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
