# Generated by Django 4.2.30 on 2026-08-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_carpeta_es_privado_carpeta_usuarios_permitidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpeta',
            name='usuarios_permitidos',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='usuarios_permitidos',
        ),
    ]
