# Generated by Django 4.2.30 on 2026-08-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_remove_carpeta_usuarios_permitidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='es_de_inspector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='es_de_inspector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='editar_inspectores',
            field=models.BooleanField(default=False, verbose_name='Editar Inspectores'),
        ),
        migrations.AddField(
            model_name='rol',
            name='ver_inspectores',
            field=models.BooleanField(default=False, verbose_name='Inspectores'),
        ),
    ]
