# Generated by Django 4.2.30 on 2026-08-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_carpeta_es_de_inspector_documento_es_de_inspector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='valor',
            field=models.IntegerField(blank=True, help_text='Valor estimado o de compra', null=True, verbose_name='Valor ($)'),
        ),
    ]
