# Generated by Django 4.2.30 on 2026-09-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_inventario_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='reuniones/'),
        ),
    ]
