# Generated by Django 4.2.30 on 2026-09-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0034_capacitacion_documento_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencia',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='emergencias_docs/'),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='registro_completado',
            field=models.BooleanField(default=False, verbose_name='Registro Completado'),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles del Incidente'),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='fecha_hora_alarma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='unidades_despachadas',
            field=models.CharField(blank=True, help_text='Ej: B-1, R-2, Z-3', max_length=100, null=True),
        ),
    ]
