# Generated by Django 4.2.23 on 2026-09-02 16:49

from django.db import migrations, models
import usuarios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_emergencia_documento_adjunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='intentos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='archivomantenimiento',
            name='archivo',
            field=models.FileField(upload_to=usuarios.validators.SecureFilePath('mantenimientos_archivos/'), validators=[usuarios.validators.validar_extension_archivo]),
        ),
        migrations.AlterField(
            model_name='archivoproyecto',
            name='archivo',
            field=models.FileField(upload_to=usuarios.validators.SecureFilePath('proyectos_archivos/'), validators=[usuarios.validators.validar_extension_archivo]),
        ),
        migrations.AlterField(
            model_name='cajachica',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=usuarios.validators.SecureFilePath('caja_chica/'), validators=[usuarios.validators.validar_extension_archivo]),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=usuarios.validators.SecureFilePath('reuniones/'), validators=[usuarios.validators.validar_extension_archivo]),
        ),
        migrations.AlterField(
            model_name='compania',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.validators.SecureFilePath('logos_companias/'), validators=[usuarios.validators.validar_extension_imagen], verbose_name='Logo de la Compañía'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=usuarios.validators.SecureFilePath('documentos/'), validators=[usuarios.validators.validar_extension_archivo]),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=usuarios.validators.SecureFilePath('emergencias_docs/'), validators=[usuarios.validators.validar_extension_archivo]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.validators.SecureFilePath('fotos_perfil/'), validators=[usuarios.validators.validar_extension_imagen], verbose_name='Foto de Perfil'),
        ),
    ]
