# Generated by Django 4.2.23 on 2026-09-02 23:08

from django.db import migrations, models
import usuarios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0036_passwordresetcode_intentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[usuarios.validators.validar_rut_chileno], verbose_name='RUT'),
        ),
    ]
